# agent profiles configuration
Zed:
  avatar: "./assets/avatar/Zed.jpg"
  zh:
    type: "文档创作"
    nick_name: "劫"
    description: "替你写文章（仿造你以前的文字风格）"
  en:
    type: "Document Creation"
    nick_name: "Zed"
    description: "Write articles for you (mimics your writing style)"

Sara:
  avatar: "./assets/avatar/Sara.jpg"
  zh:
    type: "求职招聘"
    nick_name: "沙拉"
    description: "帮你在BOSS直聘上找岗位并给BOSS打招呼"
  en:
    type: "Job & Recruitment"
    nick_name: "Sara"
    description: "Auto-apply for jobs on BOSS Zhipin"

Graves:
  avatar: "./assets/avatar/Graves.jpg"
  zh:
    type: "求职招聘"
    nick_name: "格雷福斯"
    description: "为你量身定制精美的简历"
  en:
    type: "Job & Recruitment"
    nick_name: "Graves"
    description: "Make a fantastic resume for you"

Gangplank:
  avatar: "./assets/avatar/Gangplank.jpg"
  zh:
    type: "求职招聘"
    nick_name: "普朗克"
    description: "帮你批量评分简历，找出最匹配的候选人"
  en:
    type: "Job & Recruitment"
    nick_name: "Gangplank"
    description: "Bulk rate CVs and find the best candidates for you"



# 以下为 Demo 补充
Riven:
  avatar: "./assets/avatar/Riven.jpg"
  zh:
    type: "图像任务"
    nick_name: "瑞雯"
    description: "示例展示"
  en:
    type: "Image Task"
    nick_name: "Riven"
    description: "Example Show"

Yasuo:
  avatar: "./assets/avatar/Yasuo.jpg"
  zh:
    type: "视频任务"
    nick_name: "亚索"
    description: "示例展示"
  en:
    type: "Video Task"
    nick_name: "Yasuo"
    description: "Example Show"

Catherine:
  avatar: "./assets/avatar/Catherine.jpg"
  zh:
    type: "音频任务"
    nick_name: "凯特琳"
    description: "示例展示"
  en:
    type: "Audio Task"
    nick_name: "Catherine"
    description: "Example Show"

Akali:
  avatar: "./assets/avatar/Akali.jpg"
  zh:
    type: "文本任务"
    nick_name: "阿卡丽"
    description: "仅供展示"
  en:
    type: "Text Task"
    nick_name: "Akali"
    description: "Just Demo"

Singed:
  avatar: "./assets/avatar/Singed.jpg"
  zh:
    type: "图像任务"
    nick_name: "辛吉德"
    description: "仅供展示"
  en:
    type: "Image Task"
    nick_name: "Singed"
    description: "Just Demo"

Jinx:
  avatar: "./assets/avatar/Jinx.jpg"
  zh:
    type: "音频任务"
    nick_name: "金克丝"
    description: "仅供展示"
  en:
    type: "Audio Task"
    nick_name: "Jinx"
    description: "Just Demo"