#项目顶层
PROJECT_NAME = ""
PROJECT_PATH = ""
SUBMIT_PATH = ""
#图奇专属
TWITHCH_TASK = ""
WEB_DRIVERS = {}
TWITCH_WORKSPACE_PATH = ""
TWITCH_SUBMIT_PATH = ""
TWITCH_SUBMIT_METADATA=[]
#艾希专属
ASHE_WORKSPACE_PATH = ""
ASHE_MATERIAL_PATH = ""
ASHE_EXTERNAL_MATERIALS = []
ASHE_SUBMIT_PATH = ""
#瑞兹专属
RYZE_WORKSPACE_PATH = ""
RYZE_SUBMIT_PATH = ""